### ISSUE TITLE
Why remove my project out to list in readme?

### ISSUE THREAD

**Issue by moonrailgun** [moleculerjs/awesome-moleculer#45]
Its looks like my repo, tailchat have been remove from section [Projects Using Moleculer]

in commit: https://github.com/moleculerjs/awesome-moleculer/commit/cfd8534d10a8adcfa5199db414fb595e097034b0

Is i make any mistake, or i place not right place? just ask.

**Comment by icebob** [comment]
that section contains companies who are using Moleculer and is generated automatically from the Moleculer site's "Who is using" list.

**Comment by moonrailgun** [comment]
@icebob Thanks for your reply

Well, its looks like should be name as  [Companies Using Moleculer] is better.

So if i wanna append my open source repo into this awesome list, which section should i place? [Examples]?

**Comment by AndreMaz** [comment]
Hi @moonrailgun 

As @icebob mentioned, to generate the Companies Using Moleculer  we're using [`companies.yml`](https://github.com/moleculerjs/site/blob/master/source/_data/companies.yml) located in moleculer/site. Link to code that fetches the data and generates the entries: https://github.com/moleculerjs/awesome-moleculer/blob/60e38020600bbcd1a200abd150c59e87cfc65c11/index.js#L176-L183

On the other hand, if you want to add your lib/module to this repo you need to add it to `modules.yml`. Then CI will generate Readme.md file with all the data. Here's the [PULL_REQUEST_TEMPLATE](https://github.com/moleculerjs/awesome-moleculer/blob/master/PULL_REQUEST_TEMPLATE.md) with all the info.

This is the PR that automates the generation of `Readme.md` https://github.com/moleculerjs/awesome-moleculer/pull/15
